/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorArchivos;
import Controlador.ControladorHidato;
import Modelo.Matriz;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Carlos Londoño - Yeison Ballesteros
 */
public class TableroUI extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    ControladorArchivos controlArchivos = new ControladorArchivos();
    ControladorHidato controlHidato = new ControladorHidato();
    Matriz matriz = new Matriz();
    
    public TableroUI() {
        initComponents();
        tblTablero.getTableHeader().setVisible(false);
        tblTablero.setOpaque(false);
        tblTablero.disable();
        jScrollPane1.enable(false);
        jScrollPane1.setBackground(Color.red);
        btnSolucion.setVisible(false);
        cbxFormato.setVisible(false);
        btnGuardar.setVisible(false);
        btnSolucionar.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        txtNumeroFilas = new javax.swing.JTextField();
        lblNumeroFilas = new javax.swing.JLabel();
        lblNumeroColumnas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroColumnas = new javax.swing.JTextField();
        cbxDificultad = new javax.swing.JComboBox<>();
        btnCrearTablero = new javax.swing.JButton();
        btnSolucion = new javax.swing.JButton();
        lblRango = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablero = new javax.swing.JTable();
        lblTextoRango = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        cbxFormato = new javax.swing.JComboBox<>();
        btnAdvertencia = new javax.swing.JButton();
        btnCargarArchivo = new javax.swing.JButton();
        btnSolucionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        lblBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(255, 0, 0));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("BIENVENIDO");

        txtNumeroFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroFilasActionPerformed(evt);
            }
        });
        txtNumeroFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroFilasKeyTyped(evt);
            }
        });

        lblNumeroFilas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumeroFilas.setForeground(new java.awt.Color(51, 51, 255));
        lblNumeroFilas.setText("Número de filas:");

        lblNumeroColumnas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumeroColumnas.setForeground(new java.awt.Color(51, 51, 255));
        lblNumeroColumnas.setText("Número de columnas:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Dificultad:");

        txtNumeroColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroColumnasActionPerformed(evt);
            }
        });
        txtNumeroColumnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroColumnasKeyTyped(evt);
            }
        });

        cbxDificultad.setBackground(new java.awt.Color(255, 51, 51));
        cbxDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Normal", "Difícil" }));
        cbxDificultad.setSelectedIndex(1);

        btnCrearTablero.setBackground(new java.awt.Color(0, 51, 255));
        btnCrearTablero.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearTablero.setText("Crear tablero");
        btnCrearTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTableroActionPerformed(evt);
            }
        });

        btnSolucion.setBackground(new java.awt.Color(0, 51, 255));
        btnSolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnSolucion.setText("Ver posible solución");
        btnSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionActionPerformed(evt);
            }
        });

        lblRango.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRango.setForeground(new java.awt.Color(51, 51, 254));
        lblRango.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRango.setText("3 < Número < 91");

        jScrollPane1.setBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));

        tblTablero.setAutoCreateRowSorter(true);
        tblTablero.setBackground(new java.awt.Color(240, 240, 240));
        tblTablero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 1, true));
        tblTablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTablero.setToolTipText("");
        tblTablero.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTablero.setGridColor(new java.awt.Color(0, 0, 153));
        tblTablero.setRowHeight(25);
        tblTablero.setSelectionForeground(new java.awt.Color(153, 153, 153));
        tblTablero.setShowHorizontalLines(true);
        tblTablero.setShowVerticalLines(true);
        tblTablero.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(tblTablero);
        tblTablero.getAccessibleContext().setAccessibleName("");

        lblTextoRango.setBackground(new java.awt.Color(250, 0, 0));
        lblTextoRango.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTextoRango.setForeground(new java.awt.Color(250, 0, 0));
        lblTextoRango.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoRango.setText("RANGO");

        btnGuardar.setBackground(new java.awt.Color(0, 51, 255));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cbxFormato.setBackground(new java.awt.Color(255, 51, 51));
        cbxFormato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija un formato", "png", "txt" }));

        btnAdvertencia.setBackground(new java.awt.Color(204, 0, 0));
        btnAdvertencia.setForeground(new java.awt.Color(255, 255, 255));
        btnAdvertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/advertencia.png"))); // NOI18N
        btnAdvertencia.setText("Advertencia");
        btnAdvertencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvertenciaActionPerformed(evt);
            }
        });

        btnCargarArchivo.setBackground(java.awt.Color.blue);
        btnCargarArchivo.setForeground(java.awt.Color.white);
        btnCargarArchivo.setText("Cargar tablero");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });

        btnSolucionar.setBackground(java.awt.Color.blue);
        btnSolucionar.setForeground(java.awt.Color.white);
        btnSolucionar.setText("Solucionar");
        btnSolucionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblRango, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTextoRango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(102, 102, 102))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(lblNumeroColumnas))
                                        .addComponent(lblNumeroFilas, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNumeroColumnas)
                                            .addComponent(cbxDificultad, 0, 112, Short.MAX_VALUE))
                                        .addComponent(txtNumeroFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(32, 32, 32))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAdvertencia)
                            .addGap(101, 101, 101))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSolucionar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrearTablero)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSolucion)
                        .addGap(89, 89, 89))))
            .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblBienvenida)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTextoRango)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRango)
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroFilas)
                            .addComponent(txtNumeroFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroColumnas)
                            .addComponent(txtNumeroColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnCrearTablero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSolucion)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCargarArchivo)
                            .addComponent(btnSolucionar))
                        .addGap(49, 49, 49)
                        .addComponent(btnAdvertencia))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            // TODO add your handling code here:
            controlArchivos.guardar(tblTablero, cbxFormato.getSelectedItem().toString(), controlHidato);
        } catch (IOException ex) {
            Logger.getLogger(TableroUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, matriz.imprimirMatriz(controlHidato.getV()));
    }//GEN-LAST:event_btnSolucionActionPerformed

    private void btnCrearTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTableroActionPerformed
        // TODO add your handling code here:
        controlHidato.crearTablero(txtNumeroFilas, txtNumeroColumnas, cbxDificultad.getSelectedItem().toString(), tblTablero,
            btnSolucion, cbxFormato, btnGuardar);
        btnSolucionar.setVisible(false);
    }//GEN-LAST:event_btnCrearTableroActionPerformed

    private void txtNumeroColumnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroColumnasKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroColumnasKeyTyped

    private void txtNumeroColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroColumnasActionPerformed
        
    }//GEN-LAST:event_txtNumeroColumnasActionPerformed

    private void txtNumeroFilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroFilasKeyTyped
       
        char c =evt.getKeyChar();
        if(!Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroFilasKeyTyped

    private void txtNumeroFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroFilasActionPerformed
       
    }//GEN-LAST:event_txtNumeroFilasActionPerformed

    private void btnAdvertenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvertenciaActionPerformed
        
        controlHidato.advertenciaStackOverFlow();
    }//GEN-LAST:event_btnAdvertenciaActionPerformed

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        if(controlHidato.mostrarMatriz(tblTablero, controlArchivos.cargarArchivo())){
            btnSolucionar.setVisible(true);
            btnSolucion.setVisible(false);
            cbxFormato.setVisible(false);
            btnGuardar.setVisible(false);
        }
        
       
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnSolucionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionarActionPerformed
       controlHidato.resolverHidato(tblTablero, btnGuardar, cbxFormato);
    }//GEN-LAST:event_btnSolucionarActionPerformed
    
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroUI().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvertencia;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnCrearTablero;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSolucion;
    private javax.swing.JButton btnSolucionar;
    private javax.swing.JComboBox<String> cbxDificultad;
    private javax.swing.JComboBox<String> cbxFormato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblNumeroColumnas;
    private javax.swing.JLabel lblNumeroFilas;
    private javax.swing.JLabel lblRango;
    private javax.swing.JLabel lblTextoRango;
    private javax.swing.JTable tblTablero;
    private javax.swing.JTextField txtNumeroColumnas;
    private javax.swing.JTextField txtNumeroFilas;
    // End of variables declaration//GEN-END:variables
}
